CREATE TABLE contrato(
    nro_contrato INTEGER PRIMARY KEY,
    descrip_contrato VARCHAR(30) NOT NULL
);

----------------INSERTs for contrato-----------------------------

INSERT INTO contrato (nro_contrato, descrip_contrato)
VALUES (1, 'Contrato de seguro de vida'),
       (2, 'Contrato de seguro de vida'),
       (3, 'Contrato de seguro de vida'),
       (4, 'Contrato accid. personales.'),
       (5, 'Contrato accid. personales.'),
       (6, 'Contrato accid. personales.'),
       (7, 'contrato de seguro de salud'),
       (8, 'contrato de seguro de salud'),
       (9, 'contrato de seguro de salud'),
       (10, 'contrato de invalidez.'),
       (11, 'contrato de invalidez.'),
       (12, 'contrato de invalidez.'),
       (13, 'Contrato de seguro de hogar'),
       (14, 'Contrato de seguro de hogar'),
       (15, 'contrato de seguro de hogar'),
       (16, 'contrato de seguro de auto'),
       (17, 'contrato de seguro de auto'),
       (18, 'contrato de seguro de auto'),
       (19, 'contrato de seguro de viaje'),
       (20, 'contrato de seguro de viaje'),
       (21, 'Contrato de seguro de viaje'),
       (22, 'Contrato de respons. civil'),
       (23, 'Contrato de respons. civil'),
       (24, 'Contrato de respons. civil'),
       (25, 'contrato de asist. en via'),
       (26, 'contrato de asist. en via'),
       (27, 'contrato de asist. en via'),
       (28, 'contrato asist. legal'),
       (29, 'contrato asist. legal'),
       (30, 'contrato asist. legal'),
       (31, 'contrato de seguro de decesos'),
       (32, 'contrato de seguro de decesos'),
       (33, 'contrato de seguro de decesos'),
       (34, 'contrato de seguro de decesos'),
       (35, 'Contrato de seguro de vida'),
       (36, 'Contrato de seguro de vida'),
       (37, 'Contrato de seguro de vida'),
       (38, 'Contrato de seguro de vida'),
       (39, 'Contrato de seguro de vida'),
       (40, 'Contrato accid. personales.'),
       (41, 'Contrato accid. personales.'),
       (42, 'Contrato accid. personales.'),
       (43, 'Contrato accid. personales.'),
       (44, 'Contrato accid. personales.'),
       (45, 'contrato de seguro de salud'),
       (46, 'contrato de seguro de salud'),
       (47, 'contrato de seguro de salud'),
       (48, 'contrato de seguro de salud'),
       (49, 'contrato de seguro de salud'),
       (50, 'contrato de invalidez.'),
       (51, 'contrato de invalidez.'),
       (52, 'contrato de invalidez.'),
       (53, 'contrato de invalidez'),
       (54, 'contrato de invalidez'),
       (55, 'Contrato de seguro de hogar'),
       (56, 'Contrato de seguro de hogar'),
       (57, 'contrato de seguro de hogar'),
       (58, 'Contrato de seguro de hogar'),
       (59, 'contrato de seguro de hogar'),
       (60, 'contrato de seguro de auto'),
       (61, 'contrato de seguro de auto'),
       (62, 'contrato de seguro de auto'),
       (63, 'contrato de seguro de auto'),
       (64, 'contrato de seguro de auto'),
       (65, 'contrato de seguro de auto'),
       (66, 'contrato de seguro de viaje'),
       (67, 'contrato de seguro de viaje'),
       (68, 'Contrato de seguro de viaje'),
       (69, 'contrato de seguro de viaje'),
       (70, 'contrato de seguro de viaje'),
       (71, 'Contrato de respons. civil'),
       (72, 'Contrato de respons. civil'),
       (73, 'Contrato de respons. civil'),
       (74, 'Contrato de respons. civil'),
       (75, 'Contrato de respons. civil'),
       (76, 'contrato de asist. en via'),
       (77, 'contrato de asist. en via'),
       (78, 'contrato de asist. en via'),
       (79, 'contrato de asist. en via'),
       (80, 'contrato de asist. en via'),
       (81, 'contrato asist. legal'),
       (82, 'contrato asist. legal'),
       (83, 'contrato asist. legal'),
       (84, 'contrato asist. legal'),
       (85, 'contrato asist. legal'),
       (86, 'contrato de seguro de decesos'),
       (87, 'contrato de seguro de decesos'),
       (88, 'contrato de seguro de decesos'),
       (89, 'contrato de seguro de decesos'),
       (90, 'contrato de seguro de decesos'),
       (91, 'Contrato de seguro de vida'),
       (92, 'Contrato de seguro de vida'),
       (93, 'Contrato de seguro de vida'),
       (94, 'Contrato accid. personales.'),
       (95, 'Contrato accid. personales.'),
       (96, 'Contrato accid. personales.'),
       (97, 'contrato de seguro de salud'),
       (98, 'contrato de seguro de salud'),
       (99, 'contrato de seguro de salud'),
       (100, 'contrato de invalidez.'),
       (101, 'contrato de invalidez.'),
       (102, 'contrato de invalidez.'),
       (103, 'Contrato de seguro de hogar'),
       (104, 'Contrato de seguro de hogar'),
       (105, 'contrato de seguro de hogar'),
       (106, 'contrato de seguro de auto'),
       (107, 'contrato de seguro de auto'),
       (108, 'contrato de seguro de auto'),
       (109, 'contrato de seguro de viaje'),
       (110, 'contrato de seguro de viaje'),
       (111, 'Contrato de seguro de viaje'),
       (112, 'Contrato de respons. civil'),
       (113, 'Contrato de respons. civil'),
       (114, 'Contrato de respons. civil'),
       (115, 'contrato de asist. en via'),
       (116, 'contrato de asist. en via'),
       (117, 'contrato de asist. en via'),
       (118, 'contrato asist. legal'),
       (119, 'contrato asist. legal'),
       (120, 'contrato asist. legal'),
       (121, 'contrato de seguro de decesos'),
       (122, 'contrato de seguro de decesos'),
       (123, 'contrato de seguro de decesos'),
       (124, 'contrato de seguro de decesos'),
       (125, 'Contrato de seguro de vida'),
       (126, 'Contrato de seguro de vida'),
       (127, 'Contrato de seguro de vida'),
       (128, 'Contrato accid. personales.'),
       (129, 'Contrato accid. personales.'),
       (130, 'Contrato accid. personales.'),
       (131, 'Contrato accid. personales.'),
       (132, 'contrato de seguro de salud'),
       (133, 'contrato de seguro de salud'),
       (134, 'contrato de seguro de salud'),
       (135, 'contrato de invalidez.'),
       (136, 'Contrato de seguro de hogar'),
       (137, 'Contrato de seguro de hogar'),
       (138, 'contrato de seguro de hogar'),
       (139, 'contrato de seguro de auto'),
       (140, 'contrato de seguro de auto'),
       (141, 'contrato de seguro de auto'),
       (142, 'contrato de seguro de viaje'),
       (143, 'contrato de seguro de viaje'),
       (144, 'Contrato de seguro de viaje'),
       (145, 'Contrato de respons. civil'),
       (146, 'Contrato de respons. civil'),
       (147, 'Contrato de respons. civil'),
       (148, 'contrato de asist. en via'),
       (149, 'contrato de asist. en via'),
       (150, 'contrato de asist. en via');

--INSERT INTO contrato (nro_contrato, descrip_contrato)
--VALUES (1, 'Contrato de seguro de vida'),
--       (2, 'Contrato de seguro de vida'),
--       (3, 'Contrato de seguro de vida'),
--       (4, 'Contrato accid. personales.'),
--       (5, 'Contrato accid. personales.'),
--       (6, 'Contrato accid. personales.'),
--       (7, 'contrato de seguro de salud'),
--       (8, 'contrato de seguro de salud'),
--       (9, 'contrato de seguro de salud'),
--       (10, 'contrato de invalidez.'),
--       (11, 'contrato de invalidez.'),
--       (12, 'contrato de invalidez.'),
--       (13, 'Contrato de seguro de hogar'),
--       (14, 'Contrato de seguro de hogar'),
--       (15, 'contrato de seguro de hogar'),
--       (16, 'contrato de seguro de auto'),
--       (17, 'contrato de seguro de auto'),
--       (18, 'contrato de seguro de auto'),
--       (19, 'contrato de seguro de viaje'),
--       (20, 'contrato de seguro de viaje'),
--       (21, 'Contrato de seguro de viaje'),
--       (22, 'Contrato de respons. civil'),
--       (23, 'Contrato de respons. civil'),
--       (24, 'Contrato de respons. civil'),
--       (25, 'contrato de asist. en via'),
--       (26, 'contrato de asist. en via'),
--       (27, 'contrato de asist. en via'),
--       (28, 'contrato asist. legal'),
--       (29, 'contrato asist. legal'),
--       (30, 'contrato asist. legal'),
--       (31, 'contrato de seguro de decesos'),
--       (32, 'contrato de seguro de decesos'),
--       (33, 'contrato de seguro de decesos'),
--       (34, 'contrato de seguro de decesos');
--